import { sql } from 'drizzle-orm';
import {
  boolean,
  check,
  index,
  integer,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

const tz = { withTimezone: true } as const;

// A function, not a shared object: each table needs its own column builders.
const timestamps = () => ({
  createdAt: timestamp('created_at', tz).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', tz).notNull().defaultNow(),
});

/** Fixed-window counters for rate limiting (spec §4, §6.6): one row per key per window. */
export const rateLimits = pgTable(
  'rate_limits',
  {
    key: text('key').notNull(),
    windowStart: timestamp('window_start', tz).notNull(),
    count: integer('count').notNull(),
  },
  (t) => [primaryKey({ columns: [t.key, t.windowStart] })],
);

/**
 * Accounts (spec §4). IDs are UUIDv7, generated by the application. Emails are stored lowercased,
 * and the unique index on lower(email) holds even if a write ever forgets to.
 */
export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey(),
    email: text('email').notNull(),
    /** An argon2id PHC string. */
    passwordHash: text('password_hash').notNull(),
    displayName: text('display_name').notNull(),
    emailVerifiedAt: timestamp('email_verified_at', tz),
    ...timestamps(),
  },
  (t) => [uniqueIndex('users_email_lower_key').on(sql`lower(${t.email})`)],
);

/** Database sessions (spec §6.1). The id is SHA-256 of the cookie token, so a leak yields nothing usable. */
export const sessions = pgTable(
  'sessions',
  {
    id: text('id').primaryKey(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', tz).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', tz).notNull(),
    lastSeenAt: timestamp('last_seen_at', tz).notNull(),
  },
  (t) => [index('sessions_user_id_idx').on(t.userId)],
);

export const EMAIL_TOKEN_PURPOSES = ['verify_email', 'reset_password'] as const;
export type EmailTokenPurpose = (typeof EMAIL_TOKEN_PURPOSES)[number];

/** Verify and reset links (spec §4, §6.5). Only the SHA-256 of each token is stored. */
export const emailTokens = pgTable(
  'email_tokens',
  {
    id: uuid('id').primaryKey(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    purpose: text('purpose', { enum: EMAIL_TOKEN_PURPOSES }).notNull(),
    tokenHash: text('token_hash').notNull().unique(),
    expiresAt: timestamp('expires_at', tz).notNull(),
    consumedAt: timestamp('consumed_at', tz),
    createdAt: timestamp('created_at', tz).notNull().defaultNow(),
  },
  (t) => [
    index('email_tokens_user_id_idx').on(t.userId),
    check('email_tokens_purpose_check', sql`${t.purpose} in ('verify_email', 'reset_password')`),
  ],
);

/**
 * One list per user (spec §2, D4), enforced by the unique owner_id rather than by hanging items off
 * users. Signup creates it. The share token is plaintext by design: the owner must always be able
 * to copy the link (spec §4).
 */
export const wishlists = pgTable('wishlists', {
  id: uuid('id').primaryKey(),
  ownerId: uuid('owner_id')
    .notNull()
    .unique()
    .references(() => users.id, { onDelete: 'cascade' }),
  title: text('title').notNull(),
  shareToken: text('share_token').notNull().unique(),
  showClaimsToOwner: boolean('show_claims_to_owner').notNull().default(false),
  ...timestamps(),
});
